; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
monitor_filters = send_on_enter
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = partitionsHugeApp.csv
board_build.extra_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DBOARD_HAS_PSRAM
	-DARDUINO_ESP32S3_DEV
    -DCONFIG_SPIRAM_USE
	-DCORE_DEBUG_LEVEL=3
    -DCONFIG_SPIRAM_USE_MALLOC=1
    -DCONFIG_SPIRAM_USE_CAPS_ALLOC=1
    ; Allocate any request larger than 1024 bytes directly in PSRAM
    -DCONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL=1024
    ; Fallback to PSRAM if internal SRAM allocation fails
    -DCONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL=65536
    -DCONFIG_ESP_COREDUMP_ENABLE_TO_NONE=1
    -DCONFIG_SPIRAM_ALLOW_BSS_SEG_EXTERNAL_MEMORY
    
monitor_speed = 115200
monitor_echo = yes

lib_deps = 
	olikraus/U8g2@^2.36.18

build_flags = 
    -Os
    -fexceptions
    -mtext-section-literals
    -mlongcalls
    -fno-common
    -fmerge-all-constants
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -Iinclude/giac -Igiac -Itommath -Iinclude/tommath 
    -Wno-unused-result
    -frtti
    -Wno-deprecated-enum-enum-conversion
    -Wno-volatile
    -Wno-template-id-cdtor
    -Wno-narrowing
    -DGIAC_GENERIC_CONSTANTS
    -DGIAC_GGB
    ;-DUSE_GMP_REPLACEMENTS
    -DBF2GMP
    ;-DHAVE_LIBMPFR
    -DHAVE_LIB_PTHREAD
    -DHAVE_NO_HOME_DIRECTORY
    -DHAVE_SYSCONF
    -DHAVE_SYS_TIMES_H
    -DHAVE_SYS_TIME_H
    -DHAVE_UNISTD_H
    -DIN_GIAC
    -DHAVE_NO_PWD_H
    ;-DSIZEOF_VOID_P=8
    -DTIMEOUT
    -DVERSION=\"1.2.3\"
    -DGIAC_CHECK_NEW
    -DESP_32
    ;-fno-exceptions

extra_scripts = pre:extra_script.py

build_unflags = 
    -fno-rtti 
    -fno-exceptions
    -O2 
    -O3

src_filter = 
    +<*>             ; Include all files by default
    -<tommath>   ; Exclude a specific subfolder

extra_configs = 
    ; Force the linker to garbage collect unreferenced code blocks
    -Wl,--gc-sections 